image: php:8.2

stages:
  - testunitaire


cache:
  paths:
    - vendor/

test-unitaire:
  stage: testunitaire
  image: php:latest
  variables:
    XDEBUG_MODE: coverage
  before_script:
    - apt-get update && apt-get -yq install git unzip zip libzip-dev zlib1g-dev
    - docker-php-ext-install zip
    - pecl install xdebug && docker-php-ext-enable xdebug
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - composer install
    - composer require --dev phpunit/phpunit phpunit/php-code-coverage
  script:
    - chmod +x ./vendor/bin/phpunit
    - ./vendor/bin/phpunit tests/ReservationTest.php


